### ISSUE TITLE
Add CONTRIBUTING guide to this repo

### ISSUE THREAD

**Issue by mbernier** [sendgrid/email-templates#1]
Grab contributing file [from here](https://github.com/sendgrid/sendgrid-python/blob/master/CONTRIBUTING.md) and make the following modifications:

- Change every instance referencing `sendgrid-python` to reference `email-templates`
## Remove:
- `Environment Variables` section
- `Development Environment` section from `improvements to the codebase`
- `Testing Multiple Versions of Python` section

## Rewrite

- `Understanding  the Codebase` to match this repo
- `Testing` to have the same information from the README in this repo

## For `Style Guide and Naming Conventions`:
- add instructions about: 
 - For new styles: create a directory in the root named after the "style"
 - For each email type: create a file in the directory, with a hyphenated name describing the email type (give the examples from paste-template)

**Comment by SillySam** [comment]
I will be keen to do this later today

**Comment by DeViL3998** [comment]
I'm doing it. but should i remove all? means the '####' that comes under '###' ?

**Comment by mptap** [comment]
@mbernier: https://github.com/sendgrid/email-templates/pull/12

**Comment by SillySam** [comment]
NO! Im doing it!

**Comment by DeViL3998** [comment]
I have done the remove and rename part.

**Comment by sahilsahu246** [comment]
can i do it now
