### ISSUE TITLE
Make current email templates compatible with SendGrid's Design Editor

### ISSUE THREAD

**Issue by mbernier** [sendgrid/email-templates#19]
Refactor one or more of the available email templates to use the modules [from our documentation](https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/design_editor.html#-Drag--Drop-Code-Examples), so that importing the template as a design editor template will work. 

You can test this by importing the template in the SendGrid UI. 

When you create the new version, do it in a file using the original file name + "_design-editor" e.g: "forgot-password_design-editor.html"

**Comment by LulaV14** [comment]
Hi @mbernier can I work on this?
