### ISSUE TITLE
HTML lint is reporting weird errors

### ISSUE THREAD

**Issue by mbernier** [sendgrid/email-templates#43]
If you know what this is or how to fix it, please let us know! 

I couldn't find bannedAttrs or for

```
[htmllint error in paste-templates/admin-created-account-welcome.html ] TypeError: bannedAttrs.forEach is not a function
[htmllint error in paste-templates/base.html ] TypeError: bannedAttrs.forEach is not a function
[htmllint error in paste-templates/digest.html ] TypeError: bannedAttrs.forEach is not a function
[htmllint error in paste-templates/email-confirmation.html ] TypeError: bannedAttrs.forEach is not a function
[htmllint error in paste-templates/password-reset_design_editor.html ] TypeError: bannedAttrs.forEach is not a function
[htmllint error in paste-templates/password-reset.html ] TypeError: bannedAttrs.forEach is not a function
[htmllint error in paste-templates/receipt.html ] TypeError: bannedAttrs.forEach is not a function
[htmllint error in paste-templates/welcome.html ] TypeError: bannedAttrs.forEach is not a function
```

**Comment by i-ron-y** [comment]
`bannedAttrs.forEach` is a function in htmllint's `attr-bans.js` ... not sure why it's throwing an error right now though...

**Comment by i-ron-y** [comment]
Okay, I think I've figured this out.

Consulting the [htmllint Options](https://github.com/htmllint/htmllint/wiki/Options) page, it seems like `"attr-bans"` isn't one of the options that accepts a format specifier (such as `"none"`). What do you intend by setting `"attr-bans": "none"`? Do you want no attributes at all to be banned (i.e. all attributes are allowed)? If that's the case, just set `"attr-bans": false`.
