### ISSUE TITLE
added label on issue and PR

### ISSUE THREAD

**Issue by jsroyal** [sendgrid/email-templates#47]
Like if issue assign somebody then "Under the progress"
and If not then like " unassigned"
so the PR/works do not get clashes.

**Comment by mbernier** [comment]
That's a great idea. @thinkingserious this is something we should talk about!

**Comment by jsroyal** [comment]
Cool! Please implement as soon as.

**Comment by mbernier** [comment]
The issue is that we would need to automate it. We can barely keep up right now, as it is. We are going to add this to our automation list so that we can build it when we have the chance!
