### ISSUE TITLE
Create a USE_CASES.md file

### ISSUE THREAD

**Issue by mbernier** [sendgrid/email-templates#56]
We want to show people how we would like them to use this repository. We had a contributor who provided a modification of the paste-templates/welcome.html email and created [paste-templates/admin-created-account-welcome.html](https://github.com/sendgrid/email-templates/blob/master/paste-templates/admin-created-account-welcome.html).

This is awesome! What we learned was that we want to have people add markedly different templates, if they add one to one of the design folders. 

So, we have an idea because this provided a perfect use case for this repo! 

Please do the following:
- Identify the differences in the content of the two emails (paste-templates/welcome.html vs paste-templates/admin-created-account-welcome.html)
- Create a USE_CASES.md file in the root of this repo with a section called "Using one of the Templates"
  - This section should explain that you can take an email template like welcome.html and modify the content for your specific email use case. 
  - Use the examples of the changes, showing the before (from welcome) and after (from admin-created-account-welcome.html)

Thanks!

**Comment by sevfitz** [comment]
I will create this!
