### ISSUE TITLE
Create your own style of paste-templates

### ISSUE THREAD

**Issue by mbernier** [sendgrid/email-templates#6]
Apply your own styles to our first email template styles: 

- Make a copy of the paste-templates directory.
- Change the new directory name to a new name for the style (be creative, but work-appropriate)
- Apply changes to the templates, whether style changes, format, whatever
- Make sure the templates continue to work in various email tools and are still responsive (the best way to do this is to use litmus)
- Publish by submitting a Pull Request

Edit: please change the word "Paste" from the original templates to match the name of your new template

**Comment by jsroyal** [comment]
@mbernier Do you mean by creating more than one template?
Or by mistake still, this issue is open?

**Comment by sevfitz** [comment]
I'll make a simple one!

**Comment by mbernier** [comment]
@jsroyal If you would like to apply a new font and color scheme to the templates that exist in paste-templates, that would be great! 

See the work that @sevfitz did in #44 - pretty awesome!!

**Comment by jsroyal** [comment]
Oh! Sure! Thanks for clear. Will send my PR.
